//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace theme.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Interview_schd
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Interview_schd()
        {
            this.Result = new HashSet<Result>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public byte[] Time { get; set; }
        public Nullable<int> Inte_id { get; set; }
        public Nullable<int> Vacc_id { get; set; }
        public Nullable<int> Apli_id { get; set; }
    
        public virtual Interviewer Interviewer { get; set; }
        public virtual Vacancy Vacancy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Result> Result { get; set; }
        public virtual applicant applicant { get; set; }
    }
}
