//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace theme.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;
    
    public partial class Vacancy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vacancy()
        {
            this.Interview_schd = new HashSet<Interview_schd>();
        }
    
        public int Id { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public string Description { get; set; }
        public string Status { get; set; }
        public Nullable<int> Hr_id { get; set; }
        public Nullable<int> Desig_id { get; set; }
        public Nullable<int> Dept_id { get; set; }
        public string Image { get; set; }
    public HttpPostedFileBase vacimg { get; set; }
        public virtual Department Department { get; set; }
        public virtual Designation Designation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Interview_schd> Interview_schd { get; set; }
        public virtual HR HR { get; set; }
    }
}
